version: '3'

services:

  node:
    image: node:11
    volumes:
      - ./:/code
    working_dir: /code
    command: npm install

  nodemon:
    image: node:11
    volumes:
      - ./:/code
    working_dir: /code
    command: npm run watch


  oanda_daemon:
    build:
      context: ./
      dockerfile: ./deployment/Dockerfile
    volumes:
      - ./:/code
    working_dir: /code
